export const ordersData = [
  {
    id: 7710,
    customerId: 10002,
    customerName: "Ali Jaber",
    orderSetterId: 4,
    deliveryManId: 60,
    delivaryCharg: 5,
    cart: [
      {
        id: "335",
        name: "شيبس  ",
        backagePrice: 1,
        unitPrice: 7,
        amount: 1,
        descountPrice: 0,
        unitName: "باكيت",
        img: "https://greenspoon.co.ke/wp-content/uploads/2018/06/Greenspoon-256.jpg",
        avilable: true,
        weight: "0.200",
        company: "الشركةالوطنية للصناعات الغذائية",
        country: "صنع في مصر ",
        desc: "حليب بقري سائل، غني بالبروتينات والمعادن، مناسب لجميع الأعمار، يساعد على توفير عناصر ضرورية، وكلام فارغ.",
        parcode: "",
        storeLocation: "0",
      },
      {
        id: "114",
        name: "جبنة مثلثات  ",
        backagePrice: 2,
        unitPrice: 4,
        amount: 3,
        descountPrice: 0,
        unitName: "علبة",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQvzg8-eZ5v_RVMlwUG0lEqv0aI0pwSTOZkRk47jG7HzHW1DSP3",
        avilable: true,
        weight: "0.200",
        company: "الشركةالوطنية للصناعات الغذائية",
        country: "صنع في مصر ",
        desc: "حليب بقري سائل، غني بالبروتينات والمعادن، مناسب لجميع الأعمار، يساعد على توفير عناصر ضرورية، وكلام فارغ.",
        parcode: "",
        storeLocation: "0",
      },
    ],
    cartTotal: 120,
    date: "00.00.00.4/12/2022",
    paymentType: "cash on delivary",
    DelivaryServiceType: "ordenary",
    isPacked: true,
    isDelivared: false,
    isPaid: false,
    isCanselled: false,
    isRejected: false,
    customerEvaluation: "no commets",
    controlNotes: "no commets",
  },
  {
    id: 7711,
    customerId: 10040,
    customerName: "وليد البشير",
    orderSetterId: 4,
    deliveryManId: 62,
    delivaryCharg: 7,
    cart: [
      {
        id: "335",
        name: "كولا  ",
        backagePrice: 1,
        unitPrice: 7,
        amount: 10,
        descountPrice: 0,
        unitName: "باكيت",
        img: "https://greenspoon.co.ke/wp-content/uploads/2018/06/Greenspoon-256.jpg",
        avilable: true,
        weight: "0.200",
        company: "الشركةالوطنية للصناعات الغذائية",
        country: "صنع في مصر ",
        desc: "حليب بقري سائل، غني بالبروتينات والمعادن، مناسب لجميع الأعمار، يساعد على توفير عناصر ضرورية، وكلام فارغ.",
        parcode: "",
        storeLocation: "0",
      },
      {
        id: "114",
        name: " عصير  ",
        backagePrice: 2,
        unitPrice: 5,
        amount: 1,
        descountPrice: 0,
        unitName: "علبة",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQvzg8-eZ5v_RVMlwUG0lEqv0aI0pwSTOZkRk47jG7HzHW1DSP3",
        avilable: true,
        weight: "0.200",
        company: "الشركةالوطنية للصناعات الغذائية",
        country: "صنع في مصر ",
        desc: "حليب بقري سائل، غني بالبروتينات والمعادن، مناسب لجميع الأعمار، يساعد على توفير عناصر ضرورية، وكلام فارغ.",
        parcode: "",
        storeLocation: "0",
      },
    ],
    cartTotal: 80,
    date: "00.00.00.4/12/2022",
    paymentType: "cash on delivary",
    DelivaryServiceType: "urgent",
    isPacked: false,
    isDelivared: false,
    isPaid: false,
    isCanselled: false,
    isRejected: false,
    customerEvaluation: "no commets",
    controlNotes: "no commets",
  },
];
